CURR_DIR=$(shell cd)

.PHONY: $(OS)

Windows_NT:
	@echo $(OS) 
	@echo -------- 1.Setting up message queue ------------
	@docker start rabbitmq-server1 && docker start rabbitmq-server2
	@echo -------- 2.Setting up build files --------------
	${shell IF NOT EXIST "${CURR_DIR}\bin" mkdir "${CURR_DIR}\src"}
	make $(OS)-build
	@echo -------- 3. Waiting for Message Queues to start --------------
	@timeout 6
	@echo -------- 4.starting servers -----------------
	make $(OS)-run

linux:
	@echo linux

linux-build:
	go build -o bin/app cmd/app/main.go

linux-run:
	./bin/app

Windows_NT-build:
	go build -o bin/app.exe cmd/app/main.go

Windows_NT-run:
	bin/app.exe 

test:
	go test ./...

clean:
	rm -rf bin