SHELL=cmd

CURR_DIR=$(shell cd)

.PHONY: windows test clean

windows:
	@echo  ------------ 1.Setting up message queue ------------
	docker start rabbitmq-server1 && docker start rabbitmq-server2
	@echo  ------------ 2.Setting up build files --------------
	${shell IF NOT EXIST "${CURR_DIR}\src" mkdir "${CURR_DIR}\src"}
	${shell IF NOT EXIST "${CURR_DIR}\src\log" mkdir "${CURR_DIR}\src\log"}
	go build -o src/app.exe main.go
	@echo  --------------- 3.starting servers -----------------
	src/app.exe

test:
	go test ./...

clean:
	rm -rf src

