SHELL=cmd

CURR_DIR=$(shell cd)

.PHONY: windows test clean

windows:
	@echo 1.Setting up message queue ------------
	@docker start rabbitmq-server1 && docker start rabbitmq-server2
	@echo 2.Setting up build files --------------
	${shell IF NOT EXIST "${CURR_DIR}\bin" mkdir "${CURR_DIR}\src"}
	@go build -o bin/app.exe .
	@echo 3. Waiting for Message Queues to start --------------
	@timeout 7
	@echo 4.starting servers -----------------
	@bin/app.exe

test:
	go test ./...

clean:
	rm -rf bin

